# Generated by Django 5.2.7 on 2025-11-06 18:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='invite_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
